// Verse data shared by the app and the Vercel functions in /api (share previews).
export const VERSES = [
  { id:1, ref:"Psalm 23:1", text:"The Lord is my shepherd; I shall not want.", book:"Psalms", category:["peace","trust","comfort"], explanation:"One of the most beloved psalms, written by King David, this verse opens a beautiful meditation on God's tender care. The image of a shepherd caring for his flock was deeply meaningful in the ancient world. A shepherd knew each sheep by name, led them to green pastures and still waters, and protected them from danger. For us today, it is a reminder that God is not a distant ruler but a loving guide who tends to our deepest needs.", example:"When you are overwhelmed by life's demands or feel spiritually dry, this verse is an anchor. Many saints recited Psalm 23 in their darkest hours, even before martyrdom, drawing peace from the certainty of God's presence." },
  { id:2, ref:"John 3:16", text:"For God so loved the world that he gave his only Son, so that everyone who believes in him might not perish but might have eternal life.", book:"John", category:["love","hope","faith"], explanation:"Often called 'the Gospel in miniature,' this verse captures the entire mystery of salvation in a single sentence. The word 'so' speaks of a love beyond measure, a love that moves from eternity into time, from the Father's heart to a manger, to a cross. In the Catholic tradition, this verse is at the heart of every Mass.", example:"When you doubt whether you are loved or worthy of God's mercy, return to this verse. St. Augustine wrote, Augustine wrote, 'Our heart is restless until it rests in Thee,' and it is John 3:16 that tells us why God pursued us: not because we earned it, but because love is His very nature." },
  { id:3, ref:"Philippians 4:13", text:"I have the strength for everything through him who empowers me.", book:"Philippians", category:["strength","courage","hope"], explanation:"St. Paul wrote this letter from prison, chained and uncertain of his fate, yet somehow radiating joy. The 'strength' he speaks of is not natural willpower but a supernatural capacity that flows from his union with Christ. This verse does not promise that God will remove every difficulty, but that He will provide the inner strength to pass through it with grace.", example:"Whether you are facing a health crisis, a difficult relationship, or a demanding season, this verse is a promise. Many Catholic athletes, caregivers, and missionaries have taken it as their life verse, not as a guarantee of success, but as a confidence in God's sustaining grace." },
  { id:4, ref:"Jeremiah 29:11", text:"For I know the plans I have for you, says the Lord, plans for your welfare and not for evil, to give you a future and a hope.", book:"Jeremiah", category:["hope","purpose","trust"], explanation:"God spoke these words to the Israelites during the Babylonian exile, one of the darkest periods in their history. Yet into that darkness came this luminous promise: God had not forgotten them. The Hebrew word for 'welfare' here is shalom, a rich word meaning wholeness, peace, and flourishing. God's plan is always oriented toward our true good.", example:"This verse has brought courage to generations of believers in times of uncertainty: job loss, illness, family crisis, personal failure. It does not promise an easy path, but it promises a purposeful one, held in the hands of a God who sees the end from the beginning." },
  { id:5, ref:"Matthew 11:28", text:"Come to me, all you who labor and are burdened, and I will give you rest.", book:"Matthew", category:["comfort","rest","peace"], explanation:"Jesus spoke these words in the midst of a culture crushed by religious legalism. He offers something radical: rest. Not laziness, but the deep refreshment of the soul that comes from abiding with Him. Catholic spirituality understands this rest as found especially in prayer, the sacraments, and the Eucharist, where we literally come to Him.", example:"In our age of constant productivity and noise, this invitation is countercultural and deeply needed. Many saints, including Thérèse of Lisieux, found their 'little way', a childlike and trusting rest in God's arms, rooted in this very promise." },
  { id:6, ref:"Romans 8:28", text:"We know that all things work for good for those who love God, who are called according to his purpose.", book:"Romans", category:["trust","hope","suffering"], explanation:"St. Paul does not say that all things are good. He says that God works all things for good. Even suffering, loss, and failure are not wasted in God's economy. The Catechism echoes this: 'God permits evil in order to draw forth some greater good.' This is the mystery of the Cross. The worst event in history became the source of the world's salvation.", example:"When something terrible happens, whether a diagnosis, a betrayal, or a loss, this verse does not minimize the pain. Instead, it invites us to trust in a God who is always at work beneath the surface of our lives, weaving even our darkest threads into a tapestry of redemption." },
  { id:7, ref:"Isaiah 40:31", text:"But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", book:"Isaiah", category:["strength","hope","renewal"], explanation:"The prophet Isaiah wrote this to a people who were exhausted: spiritually, physically, emotionally. Eagles do not flap their wings frantically to fly; they spread them wide and let the thermal winds carry them upward. Hoping in the Lord is like that: an act of surrender and trust that allows God's wind to lift us.", example:"Caregivers, parents, ministers, and anyone running on empty find deep resonance here. The promise is not that we will never tire, but that in waiting on God, we will find a strength that transcends our natural limits." },
  { id:8, ref:"Psalm 46:10", text:"Be still and know that I am God!", book:"Psalms", category:["peace","prayer","trust"], explanation:"In just eight words, this verse captures the entire spirituality of contemplative prayer. The word 'still' in Hebrew means to let go, to release, to slacken. It is an invitation, even a command, to stop our frantic activity and simply know God. In Catholic tradition, this verse is at the heart of contemplative life, from the Desert Fathers to the Carmelites.", example:"In an overstimulated world, this verse is medicine. Spending even five minutes in silent prayer, sitting with this verse and breathing it in, can reorient an entire day. St. Teresa of Ávila called this kind of prayer the 'prayer of quiet,' a gift that begins when we finally stop talking and simply rest." },
  { id:9, ref:"1 Corinthians 13:4-5", text:"Love is patient, love is kind. It is not jealous, it is not pompous, it is not inflated, it is not rude, it does not seek its own interests.", book:"1 Corinthians", category:["love","relationships","virtue"], explanation:"St. Paul's great hymn to love is perhaps the most quoted passage at Catholic weddings. But its original context was a divided, quarreling church. Paul wrote it not as a romantic poem but as a challenge. Every quality he describes is a concrete, demanding practice. Patience, kindness, and the refusal to keep score are not feelings but choices.", example:"Try replacing the word 'love' in this passage with your own name and see where it challenges you. This is what many spiritual directors suggest. It reveals where we fall short and points us toward the transformation God desires." },
  { id:10, ref:"Proverbs 3:5-6", text:"Trust in the Lord with all your heart, on your own intelligence do not rely. In all your ways be mindful of him, and he will make straight your paths.", book:"Proverbs", category:["trust","guidance","wisdom"], explanation:"This wisdom cuts to the heart of the spiritual life: the battle between self-reliance and trust in God. The Hebrew word for 'trust' implies leaning on something, the way you lean against a wall and trust it to hold you. True wisdom begins not with our own analysis but with a humble openness to God's guidance.", example:"When facing a major life decision, whether career, relationships, or education, this verse is a practical guide. It does not mean we stop thinking, but that we subordinate our thinking to prayer, trusting that God will illumine what we cannot see on our own." },
  { id:11, ref:"John 14:27", text:"Peace I leave with you; my peace I give to you. Not as the world gives do I give it to you. Do not let your hearts be troubled or afraid.", book:"John", category:["peace","comfort","faith"], explanation:"Jesus spoke these words at the Last Supper, hours before His arrest. Even in that shadow, He offered peace. Not the world's fragile peace of favorable circumstances, but His own divine peace. This is the peace that the martyrs faced death with, that the saints found in prison cells and sickbeds.", example:"This verse is a powerful antidote to anxiety. When worry grips the heart, praying these words slowly can be transformative. Many Catholics pray this verse in Eucharistic adoration, allowing Christ's peace to settle into the deepest places of fear." },
  { id:12, ref:"Lamentations 3:22-23", text:"The Lord's acts of mercy are not exhausted, his compassion is not spent; they are renewed each morning — great is your faithfulness!", book:"Lamentations", category:["mercy","hope","renewal"], explanation:"This luminous verse appears in one of Scripture's most desolate books, written in the ruins of Jerusalem. And yet in that rubble, the author discovers something unshakeable: God's mercies are new every morning. In Catholic spirituality, every morning Mass echoes this: a new day, a new celebration of God's faithful love.", example:"For anyone who has fallen, failed, or feels trapped in guilt, this verse is resurrection language. God's mercy does not run out. Yesterday's failures do not exhaust today's grace. Each morning is a fresh start, offered freely by a faithful God." },
  { id:13, ref:"Luke 1:37", text:"For nothing will be impossible for God.", book:"Luke", category:["faith","hope","trust"], explanation:"The angel Gabriel spoke these words to Mary at the Annunciation. It is the great declaration of divine omnipotence, spoken to reassure a young woman asked to do the humanly impossible. In Catholic tradition, this verse is treasured especially in Marian prayer, reminding us that Mary's 'yes' to the impossible is a model for our own surrender to God's will.", example:"When a situation seems beyond all hope, whether a prodigal child, a broken marriage, or an impossible dream, this verse is an anchor." },
  { id:14, ref:"Matthew 5:4", text:"Blessed are they who mourn, for they will be comforted.", book:"Matthew", category:["grief","comfort","hope"], explanation:"This verse comes from the Beatitudes, Jesus' revolutionary re-ordering of what it means to be blessed. In a world that prizes happiness and avoidance of pain, Jesus blesses those who mourn. The word 'comforted' shares a root with Paraclete, which is the Holy Spirit. Our grief is met by the very Spirit of God.", example:"In times of loss, whether death, divorce, or disappointment, this beatitude gives grief its rightful place. The Catholic tradition of All Souls' Day and funeral Masses honors the reality of mourning while pointing always toward comfort and resurrection." },
  { id:15, ref:"Psalm 34:18", text:"The Lord is close to the brokenhearted, saves those whose spirit is crushed.", book:"Psalms", category:["grief","comfort","healing"], explanation:"Rather than being distant from weakness, the Lord draws near to it. 'Brokenhearted' in Hebrew describes a heart shattered like a clay pot, completely broken. And it is precisely there that God is closest. This is the logic of the Incarnation: God does not observe our suffering from above but enters it, taking on our flesh, our tears, our death.", example:"For anyone in the depths of grief, depression, failure, or rejection, this verse is a lifeline. Many saints wrote of their 'dark nights of the soul,' and in the midst of them found that God had been nearest precisely when He seemed most absent." },
];

export const DAILY_VERSES = [
  { ref:"Psalm 23:1", text:"The Lord is my shepherd; I shall not want.", category:["peace","trust"], explanation:"King David meditates on God as a shepherd who tends to every need, knowing each sheep by name and leading them to green pastures. For us today, it is a reminder that God is not a distant ruler but a loving guide.", example:"When anxiety rises today, pray this verse slowly and let it anchor you." },
  { ref:"John 3:16", text:"For God so loved the world that he gave his only Son, so that everyone who believes in him might not perish but might have eternal life.", category:["love","hope"], explanation:"Called the Gospel in miniature, this verse captures the entire mystery of salvation. God's love is not passive. It moves Him to give His most precious gift for our sake.", example:"When you doubt whether you are loved, return to this verse. You were worth the Cross." },
  { ref:"Philippians 4:13", text:"I have the strength for everything through him who empowers me.", category:["strength","courage"], explanation:"Paul wrote this from prison, yet radiating joy. The strength he speaks of is not willpower but a supernatural grace that flows from union with Christ.", example:"Whatever you are facing today, claim this promise. Not your strength. His." },
  { ref:"Jeremiah 29:11", text:"For I know the plans I have for you, says the Lord, plans for your welfare and not for evil, to give you a future and a hope.", category:["hope","trust"], explanation:"Spoken to Israel in exile, this promise shines brightest in darkness. God's plan is always oriented toward our true flourishing, even when we cannot see it.", example:"In uncertainty, write this verse somewhere visible as a daily anchor." },
  { ref:"Matthew 11:28", text:"Come to me, all you who labor and are burdened, and I will give you rest.", category:["comfort","rest"], explanation:"Jesus offers radical rest: not laziness, but the deep refreshment that comes from abiding with Him. Catholic spirituality finds this rest especially in prayer and the Eucharist.", example:"Spend five quiet minutes today simply resting in God's presence." },
  { ref:"Romans 8:28", text:"We know that all things work for good for those who love God, who are called according to his purpose.", category:["trust","hope"], explanation:"Paul does not say all things are good. He says God works all things for good. Even suffering is not wasted in His economy.", example:"Name one difficult thing in your life and offer it to God with trust." },
  { ref:"Isaiah 40:31", text:"Those who hope in the Lord will renew their strength. They will soar on wings like eagles.", category:["strength","renewal"], explanation:"Eagles soar by letting thermal winds lift them. Hoping in God is just like that: an act of surrender that allows His wind to carry us.", example:"Instead of striving harder today, try surrendering more deeply." },
  { ref:"Psalm 46:10", text:"Be still and know that I am God!", category:["peace","prayer"], explanation:"Eight words that capture the entire spirituality of contemplative prayer. The Hebrew word for still means to let go, to release, to slacken.", example:"Set a timer for three minutes. Sit in silence with just this verse." },
  { ref:"Proverbs 3:5-6", text:"Trust in the Lord with all your heart, on your own intelligence do not rely. In all your ways be mindful of him, and he will make straight your paths.", category:["trust","wisdom"], explanation:"The Hebrew word for trust implies leaning on something, the way you lean against a wall. True wisdom begins with humble openness to God.", example:"Before making a decision today, pause and ask God to illumine your thinking." },
  { ref:"John 14:27", text:"Peace I leave with you; my peace I give to you. Not as the world gives do I give it to you.", category:["peace","comfort"], explanation:"Spoken at the Last Supper, hours before His arrest. Even in that shadow, Jesus offered His own divine peace. Not the world's fragile peace of favorable circumstances, but something that runs much deeper.", example:"When worry grips you, pray these words slowly and let Christ's peace settle in." },
  { ref:"Lamentations 3:22-23", text:"The Lord's acts of mercy are not exhausted, his compassion is not spent; they are renewed each morning — great is your faithfulness!", category:["mercy","hope"], explanation:"Written in the ruins of Jerusalem, yet discovering something unshakeable: God's mercies are new every morning. Yesterday's failures do not exhaust today's grace.", example:"Begin today by receiving God's mercy fresh, whatever yesterday looked like." },
  { ref:"Luke 1:37", text:"For nothing will be impossible for God.", category:["faith","hope"], explanation:"These are Gabriel's words to Mary at the Annunciation, a great declaration of divine omnipotence, spoken to reassure a young woman asked to do the humanly impossible.", example:"Name the one thing that seems impossible in your life and pray this verse over it." },
  { ref:"Psalm 34:18", text:"The Lord is close to the brokenhearted, saves those whose spirit is crushed.", category:["grief","comfort"], explanation:"God does not observe our suffering from a distance. He draws near to it. Brokenhearted in Hebrew describes a heart shattered like a clay pot, and it is precisely there God is closest.", example:"If your heart is heavy today, know that this is exactly where God chooses to dwell." },
  { ref:"Romans 8:38-39", text:"Nothing will be able to separate us from the love of God in Christ Jesus our Lord.", category:["love","faith"], explanation:"Paul lists every conceivable power and declares that none of them can sever the bond of God's love for us.", example:"Recite this verse as a declaration today, especially over your greatest fear." },
  { ref:"Isaiah 41:10", text:"Do not fear, for I am with you; do not be afraid, for I am your God. I will strengthen you, I will help you.", category:["courage","trust"], explanation:"God speaks directly into fear. The command not to fear is an invitation to anchor in a deeper reality: His presence and power.", example:"Write down what you are afraid of, then read this verse over it as a prayer." },
  { ref:"Psalm 121:1-2", text:"I lift up my eyes to the mountains — where does my help come from? My help comes from the Lord, the maker of heaven and earth.", category:["trust","strength"], explanation:"A pilgrim's prayer lifting eyes above the immediate terrain to the God who transcends all created things and yet is personally close.", example:"When overwhelmed today, literally look upward and pray this verse." },
  { ref:"Matthew 6:33", text:"Seek first the kingdom of God and his righteousness, and all these things will be given you besides.", category:["trust","wisdom"], explanation:"Jesus reorders our priorities entirely. Anxiety about provision is addressed not by earning more but by seeking God first.", example:"Before checking your phone this morning, spend five minutes with God." },
  { ref:"1 Corinthians 13:4-5", text:"Love is patient, love is kind. It is not jealous, it is not pompous, it is not inflated, it is not rude.", category:["love","virtue"], explanation:"Written to a quarreling church, not as poetry but as a challenge. Every quality described is not a feeling but a concrete daily choice.", example:"Replace the word love with your own name and see where it challenges you today." },
  { ref:"Hebrews 11:1", text:"Faith is the realization of what is hoped for and evidence of things not seen.", category:["faith","hope"], explanation:"The great definition of faith: not blind optimism, but a real participation in realities that transcend our physical senses, grounded in God's proven faithfulness.", example:"Name one thing you are hoping for that you cannot yet see and place it in God's hands." },
  { ref:"1 Peter 5:7", text:"Cast all your worries upon him because he cares for you.", category:["trust","peace"], explanation:"Peter invites us to throw our anxieties onto God. Not politely hand them over, but really cast them with force. The reason is simply: He cares for you personally.", example:"Name your worries one by one today and deliberately cast each one to God in prayer." },
  { ref:"Psalm 27:1", text:"The Lord is my light and my salvation; whom do I fear? The Lord is my life's refuge; of whom am I afraid?", category:["courage","faith"], explanation:"David faces real enemies and real danger yet speaks with remarkable calm. His security comes not from circumstances but from confidence in God.", example:"Face your greatest fear today and let this verse be your response to it." },
  { ref:"John 15:5", text:"I am the vine, you are the branches. Whoever remains in me and I in him will bear much fruit, because without me you can do nothing.", category:["faith","wisdom"], explanation:"Jesus uses the most organic of images to describe our relationship with Him. Fruitfulness is not effort but connection.", example:"Ask yourself: am I staying connected to the vine, or am I trying to bear fruit on my own?" },
  { ref:"Micah 6:8", text:"You have been told, O mortal, what is good, and what the Lord requires of you: only to do justice and to love goodness, and to walk humbly with your God.", category:["wisdom","virtue"], explanation:"The prophet distills the entire Law to three things. Justice, mercy, and humility are not additions to faith. They are its natural expression.", example:"Choose one of these three to focus on deliberately today." },
  { ref:"Zephaniah 3:17", text:"The Lord your God is in your midst, a mighty savior. He will rejoice over you with gladness and renew you in his love.", category:["love","peace"], explanation:"One of Scripture's most tender images: God rejoicing over us. Not tolerating us, not merely forgiving us, but delighting in us with gladness.", example:"Sit quietly and let yourself receive this: God rejoices over you right now, today." },
  { ref:"Sirach 2:6", text:"Trust in God, and he will help you; make straight your ways and hope in him.", category:["trust","hope"], explanation:"From the Wisdom tradition of the Catholic Bible, this verse offers a simple and direct path through difficulty: trust, straighten your path, and hope.", example:"Is there an area of your life where your path needs straightening? Bring it to God today." },
  { ref:"Wisdom 3:1", text:"The souls of the righteous are in the hand of God, and no torment shall touch them.", category:["comfort","faith"], explanation:"A profound source of consolation for those grieving the loss of loved ones. Death does not have the final word. The righteous are held safely in God's own hand.", example:"If you have lost someone you love, pray this verse for them today." },
  { ref:"Psalm 139:14", text:"I praise you, because I am wonderfully made; wonderful are your works! My very self you know.", category:["love","faith"], explanation:"David meditates on God's intimate knowledge of him. You are not an accident but a deliberate and wonderful work of God.", example:"Say this verse about yourself today, even if it feels difficult to believe." },
  { ref:"Isaiah 43:1", text:"Do not fear, for I have redeemed you; I have called you by name: you are mine.", category:["love","comfort"], explanation:"God addresses each person not as a number or a category but by name. You are personally known, personally called, and personally claimed by God.", example:"Hear God speak your own name as you read this verse. You belong to Him." },
  { ref:"Colossians 3:23", text:"Whatever you do, do from the heart, as for the Lord and not for others.", category:["wisdom","strength"], explanation:"Paul elevates every form of work to an act of worship. The dishwasher, the caregiver, the clerk: all can work as for the Lord.", example:"Offer your work today, all of it, as a prayer to God." },
  { ref:"Galatians 5:22-23", text:"The fruit of the Spirit is love, joy, peace, patience, kindness, generosity, faithfulness, gentleness, self-control.", category:["virtue","renewal"], explanation:"Paul lists not achievements but fruit, something that grows naturally from a living connection with the Spirit. These qualities are not manufactured but cultivated.", example:"Which fruit of the Spirit do you most need to grow right now? Ask the Spirit for it." },
  { ref:"Ephesians 2:10", text:"We are God's handiwork, created in Christ Jesus for the good works that God has prepared in advance.", category:["purpose","faith"], explanation:"The Greek word for handiwork is poiema, which means poem. You are God's poem, composed with care and intention, created for works He already has in mind for you.", example:"Ask God today what good work He has prepared for you and take one step toward it." },
  { ref:"Psalm 103:8", text:"Merciful and gracious is the Lord, slow to anger, abounding in kindness.", category:["mercy","love"], explanation:"This description of God's character appears repeatedly in Scripture. God is not reluctant to show mercy; He abounds in it.", example:"Receive this truth personally today: God abounds in kindness toward you." },
  { ref:"2 Corinthians 12:9", text:"My grace is sufficient for you, for power is made perfect in weakness.", category:["strength","trust"], explanation:"God's response to Paul's suffering is not removal of the thorn but the gift of grace within it. Divine power reaches its fullest expression through human weakness.", example:"Name your greatest weakness today and offer it to God as the place where His power can work." },
  { ref:"Psalm 16:8", text:"I keep the Lord always before me; with the Lord at my right hand, I shall never be shaken.", category:["peace","faith"], explanation:"David's secret of stability is not the absence of threats but the constancy of God's presence.", example:"Set a reminder today to pause three times and simply acknowledge God's presence with you." },
  { ref:"Romans 15:13", text:"May the God of hope fill you with all joy and peace in believing, so that you may abound in hope by the power of the Holy Spirit.", category:["hope","peace"], explanation:"Paul prays for an overflowing of hope: not a cautious optimism, but an abundance powered not by willpower but by the Holy Spirit.", example:"Pray this verse over yourself and over someone you know who needs hope today." },
  { ref:"2 Maccabees 12:46", text:"It is a holy and wholesome thought to pray for the dead, that they may be loosed from sins.", category:["faith","mercy"], explanation:"This deuterocanonical text is the scriptural foundation for the Church's teaching on prayer for the dead, a uniquely Catholic and deeply consoling doctrine.", example:"Pray for someone who has died today, whether a family member, a friend, or a forgotten soul." },
  { ref:"Matthew 18:20", text:"For where two or three are gathered together in my name, there am I in the midst of them.", category:["faith","community"], explanation:"Jesus promises His presence not only in solitary prayer but in the gathered community. The Church is a place where Christ is personally present.", example:"Pray with at least one other person today, even briefly, claiming this promise." },
  { ref:"Psalm 118:24", text:"This is the day the Lord has made; let us rejoice in it and be glad.", category:["joy","gratitude"], explanation:"Originally a liturgical shout at the Temple, now prayed by the whole Church. Every day, even a difficult one, is a gift made by God and worthy of gratitude.", example:"Say this verse aloud when you wake up tomorrow and mean it, whatever the day holds." },
  { ref:"Tobit 4:15", text:"Do to no one what you yourself dislike. Give to the hungry some of your bread, and to the naked some of your clothing.", category:["virtue","love"], explanation:"From the deuterocanonical book of Tobit, a father's wisdom to his son. The golden rule and concrete charity: two pillars of a life well-lived.", example:"Do one concrete act of generosity today for someone who cannot repay you." },
  { ref:"Isaiah 55:8-9", text:"For my thoughts are not your thoughts, nor are your ways my ways, says the Lord. For as the heavens are higher than the earth, so are my ways higher than your ways.", category:["trust","wisdom"], explanation:"A radical invitation to humility before the mystery of God. What seems like failure or loss may be part of a design too large for us to see from where we stand.", example:"Release something today that you have been trying to control and trust God's higher way." },
  { ref:"Revelation 21:4", text:"He will wipe every tear from their eyes, and there shall be no more death or mourning, wailing or pain, for the old order has passed away.", category:["hope","comfort"], explanation:"The final vision of Scripture: God personally wiping every tear. This is not escapism but the ultimate destination of all Christian hope.", example:"Let this vision of the end comfort you in whatever you are suffering today. This is where we are headed." },
  { ref:"Psalm 91:1-2", text:"You who dwell in the shelter of the Most High, who abide in the shade of the Almighty, say to the Lord: my refuge and fortress, my God in whom I trust.", category:["trust","peace"], explanation:"An image of profound safety: dwelling not just near God but within Him, sheltered by His very presence.", example:"Begin your day by consciously placing yourself within God's shelter through prayer." },
  { ref:"John 8:12", text:"I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life.", category:["faith","hope"], explanation:"One of the great I AM statements of Jesus. He does not merely show a path. He is the light that makes the path visible.", example:"In whatever feels dark in your life today, ask Jesus to be your light in it." },
  { ref:"Acts 1:8", text:"You will receive power when the Holy Spirit comes upon you, and you will be my witnesses.", category:["faith","courage"], explanation:"The last words of Jesus before the Ascension. The disciples are sent not in their own strength but promised the power of the Holy Spirit.", example:"Ask the Holy Spirit today to empower you as a witness in your ordinary life." },
  { ref:"1 John 4:18", text:"There is no fear in love, but perfect love drives out fear.", category:["love","peace"], explanation:"The logic of love and fear are mutually exclusive. As we grow in the experience of God's love, fear loses its grip.", example:"Identify one fear you carry and ask God to replace it with a deeper awareness of His love." },
  { ref:"Deuteronomy 31:6", text:"Be strong and steadfast; do not fear or be dismayed, for the Lord, your God, who goes before you, will be with you.", category:["courage","trust"], explanation:"Moses speaks to a people entering unknown territory. The basis for courage is not the absence of danger but the presence of God who goes before them.", example:"Whatever you are entering into today, remember: God goes before you." },
  { ref:"James 1:17", text:"Every good gift and every perfect gift is from above, coming down from the Father of lights.", category:["gratitude","love"], explanation:"James roots all goodness in God's generous nature. The gifts of life, beauty, love, friendship, and talent are all expressions of the Father's lavish generosity.", example:"Name three good things in your life today and trace them back to God as their source." },
  { ref:"Psalm 62:1-2", text:"My soul rests in God alone, from whom comes my salvation. God alone is my rock and salvation, my fortress; I shall never fall.", category:["trust","peace"], explanation:"The Hebrew for rests means a silence of complete surrender. Not passive resignation but active trust that has found its resting place in God alone.", example:"Practice resting in God today: not solving, not striving, just trusting." },
  { ref:"Sirach 3:17", text:"My child, conduct your affairs with humility, and you will be loved more than a giver of gifts.", category:["wisdom","virtue"], explanation:"Ben Sira's wisdom cuts against the grain of a world that prizes power and display. Genuine humility draws love that no gift can purchase.", example:"Practice one act of genuine humility today, unseen and unannounced." },
  { ref:"Matthew 5:9", text:"Blessed are the peacemakers, for they will be called children of God.", category:["peace","virtue"], explanation:"Peacemakers in the ancient world actively worked to reconcile divided parties, often at personal cost. This is the family resemblance of God's children.", example:"Is there a relationship in your life that needs a peacemaker today? Could that be you?" },
];

// Stable, URL-safe key for a verse reference, e.g. "Psalm 23:1" -> "psalm-23-1".
export function verseSlug(ref) {
  return String(ref || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

// Looks a verse up by slug across both lists (first match wins). Returns { ref, text } or null.
export function findVerse(slug) {
  if (!slug) return null;
  const hit = [...VERSES, ...DAILY_VERSES].find((x) => verseSlug(x.ref) === slug);
  return hit ? { ref: hit.ref, text: hit.text } : null;
}
